name: Deployment to Dev environment
on: pull_request
jobs:
  bump_version:
    name: Bump Version change
    runs-on: ubuntu-latest
    steps:
      - name: Update the Version
        #run: echo 'Bumping version...'
        uses: actions/checkout@v4
        with:
          refs: '.'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "custom-github@yahoo.in"
      - name: Authenticate GH CLI
        run: |
          echo "${{ secrets.BOT_SECURITY_KEY }}" | gh auth login --with-token
      - name: update Version in package.json
        run: |
          npm i
          echo 'npm version $(npm -v)'
          # Get the triggered branch name
          TRIGGERED_BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          # Generate a unique branch name (e.g., bump-rc-versions-timestamp)
          NEW_BRANCH_NAME="bump-rc-versions-$(date +"%Y-%m-%d")-${{ github.run_number }}"
          git checkout -b $NEW_BRANCH_NAME
          node -e 'const fs = require("fs"); const packageJson = JSON.parse(fs.readFileSync("package.json", "utf8")); packageJson.version = "1.0.0"; fs.writeFileSync("package.json", JSON.stringify(packageJson, null, 2));'
          git add .
          git commit -m "Bump version to 1.0.0"
          git push origin HEAD:refs/heads/bump-version
          gh pr create --base "$TRIGGERED_BRANCH" --head "$NEW_BRANCH_NAME" --title "Bump RC versions" --body "Automated bump of RC versions."

  publish_to_repo:
    name: Publish to Repo
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Jfrog
        run: echo 'Publishing to Jfrog...'
  update_packages_on_bb:
    name: Update packages & create a branch on BB
    needs: [bump_version, publish_to_repo]
    runs-on: ubuntu-latest
    steps:
      - name: Update packages on Bitbucket
        run: echo 'Updating packages on Bitbucket...'
