name: Deployment to Dev environment
on: push
jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Update the Version
        run: echo 'Bumping version...'
  publish_to_repo:
    name: Publish to Repo
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Jfrog
        run: echo 'Publishing to Jfrog...'
  update_packages_on_bb:
    name: Update packages & create a branch on BB
    needs: [bump_version, publish_to_repo]
    runs-on: ubuntu-latest
    steps:
      - name: Update packages on Bitbucket
        run: echo 'Updating packages on Bitbucket...'
