name: Deployment to Dev environment
on: [workflow_dispatch, pull_request]

jobs:
  bump_version:
    name: Bump Version change
    runs-on: ubuntu-latest
    env:
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Update the Version
        #run: echo 'Bumping version...'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          refs: '.'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Pull before pushing
        run: |
          git pull origin test-pr-gha --rebase
          git push origin your-branch-name
      - name: update Version in package.json
        run: |
          npm i
          echo "npm version $(npm -v)"

          TRIGGERED_BRANCH=$(echo "${GITHUB_REF#refs/heads/}")

          NEW_BRANCH_NAME="bump-rc-versions-$(date +"%Y-%m-%d")-${RUN_NUMBER}"

          git checkout -b "$NEW_BRANCH_NAME"

          node -e '
            const fs = require("fs");
            const packageJson = JSON.parse(fs.readFileSync("package.json", "utf8"));
            packageJson.version = "1.0.0";
            fs.writeFileSync("package.json", JSON.stringify(packageJson, null, 2));
          '

          git add .
          git commit -m "Bump version to 1.0.0"

          gh pr create --base "$TRIGGERED_BRANCH" --head "$NEW_BRANCH_NAME" --title "Bump RC versions" --body "Automated bump of RC versions."
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_to_repo:
    name: Publish to Repo
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Jfrog
        run: echo 'Publishing to Jfrog...'

  update_packages_on_bb:
    name: Update packages & create a branch on BB
    needs: [bump_version, publish_to_repo]
    runs-on: ubuntu-latest
    steps:
      - name: Update packages on Bitbucket
        run: echo 'Updating packages on Bitbucket...'
